CLUTTEX = cluttex --engine uplatex --shell-escape -output-directory myout
ADDOPTIONS = # as like as ... --includeonly

VOL1STYFILES   = CJK-char-convert.sty sora-utsu-nami-debug.sty bxglyphwiki.sty jdkintou.sty sfkanbun.sty indent.sty
VOL2STYFILES   = CJK-char-convert.sty sora-utsu-nami-debug.sty bxglyphwiki.sty jdkintou.sty sfkanbun.sty indent.sty warichu.sty
VOL3STYFILES   = CJK-char-convert.sty sora-utsu-nami-debug.sty bxglyphwiki.sty jdkintou.sty sfkanbun.sty indent.sty
VOLALLSTYFILES = CJK-char-convert.sty sora-utsu-nami-debug.sty bxglyphwiki.sty jdkintou.sty sfkanbun.sty

VOL1TARGET			= vol-1-天うつ浪第一
VOL2TARGET			= vol-2-天うつ浪第二
VOL3TARGET			= vol-3-天うつ浪第三
VOLALLTARGET		= vol-all-天うつ浪
VOLALLDEBUGTARGET	= vol-all-天うつ浪-debug

VOL1TEXFILE			= $(VOL1TARGET).tex
VOL2TEXFILE			= $(VOL2TARGET).tex
VOL3TEXFILE			= $(VOL3TARGET).tex
VOLALLTEXFILE		= $(VOLALLTARGET).tex
VOLALLDEBUGTEXFILE	= $(VOLALLDEBUGTARGET).tex

VOL1TEXFILES =	001-1-01-其一.tex     002-1-02-其二.tex     003-1-03-其三.tex     004-1-04-其四.tex     005-1-05-其五.tex		\
				006-1-06-其六.tex     007-1-07-其七.tex     008-1-08-其八.tex     009-1-09-其九.tex     010-1-10-其十.tex		\
				011-1-11-其十一.tex   012-1-12-其十二.tex   013-1-13-其十三.tex   014-1-14-其十四.tex   015-1-15-其十五.tex		\
				016-1-16-其十六.tex   017-1-17-其十七.tex   018-1-18-其十八.tex   019-1-19-其十九.tex   020-1-20-其二十.tex		\
				021-1-21-其二十一.tex 022-1-22-其二十二.tex 023-1-23-其二十三.tex 024-1-24-其二十四.tex 025-1-25-其二十五.tex	\
				026-1-26-其二十六.tex 027-1-27-其二十七.tex 028-1-28-其二十八.tex 029-1-29-其二十九.tex 030-1-30-其三十.tex		\
				031-1-31-其三十一.tex 032-1-32-其三十二.tex 033-1-33-其三十三.tex 034-1-34-其三十四.tex 035-1-35-其三十五.tex	\
				036-1-36-其三十六.tex 037-1-37-其三十七.tex 038-1-38-其三十八.tex 039-1-39-其三十九.tex 040-1-40-其四十.tex

VOL2TEXFILES =	041-2-01-其一.tex     042-2-02-其二.tex     043-2-03-其三.tex     044-2-04-其四.tex     045-2-05-其五.tex		\
				046-2-06-其六.tex     047-2-07-其七.tex     048-2-08-其八.tex     049-2-09-其九.tex     050-2-10-其十.tex		\
				051-2-11-其十一.tex   052-2-12-其十二.tex   053-2-13-其十三.tex   054-2-14-其十四.tex   055-2-15-其十五.tex		\
				056-2-16-其十六.tex   057-2-17-其十七.tex   058-2-18-其十八.tex   059-2-19-其十九.tex   060-2-20-其二十.tex		\
				061-2-21-其二十一.tex 062-2-22-其二十二.tex 063-2-23-其二十三.tex 064-2-24-其二十四.tex 065-2-25-其二十五.tex	\
				066-2-26-其二十六.tex 067-2-27-其二十七.tex 068-2-28-其二十八.tex 069-2-29-其二十九.tex 070-2-30-其三十.tex		\
				071-2-31-其三十一.tex 072-2-32-其三十二.tex 073-2-33-其三十三.tex 074-2-34-其三十四.tex 075-2-35-其三十五.tex	\
				076-2-36-其三十六.tex 077-2-37-其三十七.tex 078-2-38-其三十八.tex 079-2-39-其三十九.tex 080-2-40-其四十.tex		\
				081-2-41-其四十一.tex 082-2-42-其四十二.tex 083-2-43-其四十三.tex 084-2-44-其四十四.tex 085-2-45-其四十五.tex	\
				086-2-46-其四十六.tex 087-2-47-其四十七.tex 088-2-48-其四十八.tex 089-2-49-其四十九.tex 090-2-50-其五十.tex		\
				091-2-51-其五十一.tex

VOL3TEXFILES =	092-3-01-其一.tex     093-3-02-其二.tex     094-3-03-其三.tex     095-3-04-其四.tex     096-3-05-其五.tex		\
				097-3-06-其六.tex     098-3-07-其七.tex     099-3-08-其八.tex     100-3-09-其九.tex     101-3-10-其十.tex		\
				102-3-11-其十一.tex   103-3-12-其十二.tex   104-3-13-其十三.tex   105-3-14-其十四.tex   106-3-15-其十五.tex		\
				107-3-16-其十六.tex   108-3-17-其十七.tex   109-3-18-其十八.tex   110-3-19-其十九.tex   111-3-20-其二十.tex		\
				112-3-21-其二十一.tex 113-3-22-其二十二.tex 114-3-23-其二十三.tex 115-3-24-其二十四.tex 116-3-25-其二十五.tex	\
				117-3-26-其二十六.tex 118-3-27-其二十七.tex 119-3-28-其二十八.tex 120-3-29-其二十九.tex 121-3-30-其三十.tex		\
				122-3-31-其三十一.tex 123-3-32-其三十二.tex 124-3-33-其三十三.tex 125-3-34-其三十四.tex 126-3-35-其三十五.tex	\
				127-3-36-其三十六.tex 128-3-37-其三十七.tex 129-3-38-其三十八.tex 130-3-39-其三十九.tex 131-3-40-其四十.tex		\
				132-3-41-其四十一.tex 133-3-42-其四十二.tex 134-3-43-其四十三.tex 135-3-44-其四十四.tex 136-3-45-其四十五.tex	\
				137-3-46-其四十六.tex 138-3-47-其四十七.tex 139-3-48-其四十八.tex 140-3-49-其四十九.tex

VOL1FILES			= $(VOL1TEXFILE)        $(VOL1STYFILES)   $(VOL1TEXFILES)
VOL2FILES			= $(VOL2TEXFILE)        $(VOL2STYFILES)   $(VOL2TEXFILES)
VOL3FILES			= $(VOL3TEXFILE)        $(VOL3STYFILES)   $(VOL3TEXFILES)
VOLALLFILES			= $(VOLALLTEXFILE)      $(VOLALLSTYFILES) $(VOL1TEXFILES) $(VOL2TEXFILES) $(VOL3TEXFILES)
VOLALLDEBUGFILES	= $(VOLALLDEBUGTEXFILE) $(VOLALLSTYFILES) $(VOL1TEXFILES) $(VOL2TEXFILES) $(VOL3TEXFILES)

.PHONY : all
all : $(VOL1TARGET).pdf $(VOL2TARGET).pdf $(VOL3TARGET).pdf

.PHONY : allall
allall : $(VOL1TARGET).pdf $(VOL2TARGET).pdf $(VOL3TARGET).pdf $(VOLALLTARGET).pdf

$(VOL1TARGET).pdf			: $(VOL1FILES)         ; $(CLUTTEX) --max-iterations 1 $(ADDOPTIONS) $< ; open $(VOL1TARGET).pdf
$(VOL2TARGET).pdf			: $(VOL2FILES)         ; $(CLUTTEX) --max-iterations 1 $(ADDOPTIONS) $< ; open $(VOL2TARGET).pdf
$(VOL3TARGET).pdf			: $(VOL3FILES)         ; $(CLUTTEX) --max-iterations 1 $(ADDOPTIONS) $< ; open $(VOL3TARGET).pdf
$(VOLALLTARGET).pdf			: $(VOLALLFILES)       ; $(CLUTTEX)                                  $< ; open $(VOLALLTARGET).pdf
$(VOLALLDEBUGTARGET).pdf	: $(VOLALLDEBUGFILES)  ; $(CLUTTEX)                                  $< ; open $(VOLALLDEBUGTARGET).pdf

$(VOL1TARGET)				: $(VOL1TEXFILES)      ; $(CLUTTEX)                    $(ADDOPTIONS) $< ; open $(VOL1TARGET).pdf
$(VOL2TARGET)				: $(VOL2TEXFILES)      ; $(CLUTTEX)                    $(ADDOPTIONS) $< ; open $(VOL2TARGET).pdf
$(VOL3TARGET)				: $(VOL3TEXFILES)      ; $(CLUTTEX)                    $(ADDOPTIONS) $< ; open $(VOL3TARGET).pdf
$(VOLALLTARGET)				: $(VOLALLTEXFILES)    ; $(CLUTTEX)                                  $< ; open $(VOLALLTARGET).pdf
$(VOLALLDEBUGTARGET)		: $(VOLALLDEBUGFILES)  ; $(CLUTTEX)                                  $< ; open $(VOLALLDEBUGTARGET).pdf

$(VOL1TARGET)-diff 			: $(VOL1TEXFILES)
	$(CLUTTEX) --output $(VOL1TARGET)-temp.pdf $(VOL1TARGET).tex
	@if [ test -f $(VOL1TARGET).pdf ] ; then \
		diff-pdf -s -m --output-diff=$(VOL1TARGET)-diff.pdf $(VOL1TARGET).pdf $(VOL1TARGET)-temp.pdf ; \
		open                         $(VOL1TARGET)-diff.pdf $(VOL1TARGET).pdf                        ; \
	fi
	open $(VOL1TARGET)-temp.pdf

$(VOL2TARGET)-diff			: $(VOL2TEXFILES)
	$(CLUTTEX) --output $(VOL2TARGET)-temp.pdf $(VOL2TARGET).tex
	@if [ test -f $(VOL2TARGET).pdf ] ; then \
		diff-pdf -s -m --output-diff=$(VOL2TARGET)-diff.pdf $(VOL2TARGET).pdf $(VOL2TARGET)-temp.pdf ; \
		open                         $(VOL2TARGET)-diff.pdf $(VOL2TARGET).pdf                        ; \
	fi
	open $(VOL2TARGET)-temp.pdf

$(VOL3TARGET)-diff			: $(VOL3TEXFILES)
	$(CLUTTEX) --output $(VOL3TARGET)-temp.pdf $(VOL3TARGET).tex
	@if [ test -f $(VOL3TARGET).pdf ] ; then \
		diff-pdf -s -m --output-diff=$(VOL3TARGET)-diff.pdf $(VOL3TARGET).pdf $(VOL3TARGET)-temp.pdf ; \
		open                         $(VOL3TARGET)-diff.pdf $(VOL3TARGET).pdf                        ; \
	fi
	open $(VOL3TARGET)-temp.pdf

$(VOLALLTARGET)-diff		: $(VOLALLTEXFILES)
	$(CLUTTEX) --output $(VOLALLTARGET)-temp.pdf $(VOLALLTARGET).tex
	@if [ test -f $(VOLALLTARGET).pdf ] ; then \
		diff-pdf -s -m --output-diff=$(VOLALLTARGET)-diff.pdf $(VOLALLTARGET).pdf $(VOLALLTARGET)-temp.pdf ; \
		open                         $(VOLALLTARGET)-diff.pdf $(VOLALLTARGET).pdf                               ; \
	fi
	open $(VOLALLTARGET)-temp.pdf

$(VOLALLDEBUGTARGET)-diff	: $(VOLALLDEBUGFILES)
	$(CLUTTEX) --output $(VOLALLDEBUGTARGET)-temp.pdf $(VOLALLDEBUGTARGET).tex
	@if [ test -f $(VOLALLDEBUGTARGET).pdf ] ; then \
		diff-pdf -s -m --output-diff=$(VOLALLDEBUGTARGET)-diff.pdf $(VOLALLDEBUGTARGET).pdf $(VOLALLDEBUGTARGET)-temp.pdf ; \
		open                         $(VOLALLDEBUGTARGET)-diff.pdf $(VOLALLDEBUGTARGET).pdf                               ; \
	fi
	open $(VOLALLDEBUGTARGET)-temp.pdf

.PHONY : clean
clean :
	- $(shell find . -maxdepth 1 -iname '*.pdf' -print -delete)

clean-myout:
	- $(shell find myout -depth -type f -not -iname do-not-remove -print -delete)

clean-mygwi:
	- $(shell find mygwi -depth -type f -not -iname do-not-remove -print -delete)

help:
	@ echo 各分冊ごとに .pdf を作成
	@ echo make
	@ echo make all
	@ echo
	@ echo 各分冊ごとに加え全三巻を一冊とした .pdf を作成
	@ echo make allall
	@ echo
	@ echo 個別に（作成日付に応じて） .pdf を作成
	@ echo make vol-1-天うつ浪第一.pdf
	@ echo make vol-2-天うつ浪第二.pdf
	@ echo make vol-3-天うつ浪第三.pdf
	@ echo make vol-all-天うつ浪.pdf
	@ echo
	@ echo 個別に強制的に .pdf を作成
	@ echo make vol-1-天うつ浪第一
	@ echo make vol-2-天うつ浪第二
	@ echo make vol-3-天うつ浪第三
	@ echo make vol-all-天うつ浪
	@ echo
	@ echo pdf の差分の pdf 作成
	@ echo make vol-1-天うつ浪第一-diff
	@ echo make vol-2-天うつ浪第二-diff
	@ echo make vol-3-天うつ浪第三-diff
	@ echo make vol-all-天うつ浪-diff
	@ echo
	@ echo includeonly を使用した例
	@ echo make vol-1-天うつ浪第一 ADDOPTIONS="--includeonly=001-1-01-其一"
	@ echo
	@ echo デバッグ用
	@ echo make vol-all-天うつ浪-debug.pdf
	@ echo make vol-all-天うつ浪-debug
	@ echo make vol-all-天うつ浪-debug-diff
